version: '3'

services:

  rabbit:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
  microservicoa:
    image: docker.io/jcpersonal/microservico-avancadev-a
    ports:
      - 9090
  microservicob:
    depends_on:
      - "rabbit"
    image: docker.io/jcpersonal/microservico-avancadev-b
    ports:
      - 9091
  microservicoc:
    image: docker.io/jcpersonal/microservico-avancadev-c
    ports:
      - 9092      